apiVersion: v1
kind: Service
metadata:
  name: albums-db-svc
  namespace: albums-app
spec:
  selector:
    app: albums-db
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP