apiVersion: v1
kind: PersistentVolume
metadata:
  name: albums-db-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/albums-pv/mongodb
