apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: albums-monitoring
  labels:
    config: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    scrape_configs:

      - job_name: "albums-api"
        
        kubernetes_sd_configs:
        - role: endpoints
        
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_albums_prometheus_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_service_annotation_albums_prometheus_scheme]
          action: replace
          target_label: __scheme__
          regex: (http?)
        - source_labels: [__meta_kubernetes_service_annotation_albums_prometheus_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_service_annotation_albums_prometheus_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_service
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod