networks:
  albums-net:
    name: albums-net
    driver: bridge

services:
  db:
    container_name: albums-db
    image: mongo
    restart: unless-stopped
    networks:
      - albums-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: changeme
          
  api:
    container_name: albums-api
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - albums-net
    depends_on:
      - db
    environment:
      MONGO_CONNECTION: mongodb://admin:changeme@db:27017

  prometheus:
    container_name: albums-prometheus
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - albums-net
    depends_on:
      - api

  grafana:
    container_name: albums-grafana
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - albums-net
    depends_on:
      - prometheus