networks:
  albums-net:
    name: albums-net
    driver: bridge

services:
  db:
    container_name: albums-db
    image: mongo
    restart: unless-stopped
    networks:
      - albums-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: changeme
          
  api:
    container_name: albums-api
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - albums-net
    depends_on:
      - db
    environment:
      MONGO_CONNECTION: mongodb://admin:changeme@db:27017
