version: '3.1'

networks:
  api-mongo:
    name: api-mongo
    driver: bridge

volumes:
  db:
    name: db

services:
  db:
    container_name: db
    image: mongo
    restart: always
    networks:
      - api-mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Example123
    volumes:
      - db:/data/db
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
          
  api:
    container_name: api
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - api-mongo
    depends_on:
      - db
    environment:
      STRING_CONNECTION: mongodb://root:Example123@db:27017
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
