apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: albums-db-pvc
  namespace: albums-app
spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
    storageClassName: standard
    volumeName: albums-db-pv
