apiVersion: v1
kind: Service
metadata:
  name: albums-api-svc
  namespace: infnet-devops
spec:
  selector:
    app: albums-api
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31001
    protocol: TCP