apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc-clusterip
  namespace: albums-monitoring
spec:
  selector:
    app: prometheus
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP