apiVersion: v1
kind: Service
metadata:
  name: grafana-svc-nodeport
  namespace: albums-monitoring
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31002
    protocol: TCP