apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: albums-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/prometheus-pv
  
