apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deploy
  namespace: albums-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus-pod
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus-account
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
              