apiVersion: v1
kind: Service
metadata:
  name: albums-api-svc-clusterip
  namespace: albums-app
  annotations:
    albums.prometheus/scrape: "true"
    albums.prometheus/scheme: "http"
    albums.prometheus/path: "/metrics"
    albums.prometheus/port: "8080"
spec:
  selector:
    app: albums-api
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP