apiVersion: apps/v1
kind: Deployment
metadata:
  name: albums-api-deploy
  namespace: albums-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: albums-api
  template:
    metadata:
      name: albums-api-pod
      labels:
        app: albums-api
    spec:
      containers:
        - name: albums-api
          image: joaoaaf/albums-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_CONNECTION
              value: mongodb://albums-db-svc.albums-app.svc.cluster.local:27017
          readinessProbe:
            initialDelaySeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 3
            httpGet:
              port: 8080
              path: /
          livenessProbe:
            initialDelaySeconds: 20
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              port: 8080
              path: /