name: Tests
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Iniciando Testes
        run: |
          echo "Iniciando testes em $(date)"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configurando Ambiente Golang
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.0'
      - name: Subindo Banco de Dados
        run: |
          docker run -d --rm --name mongodb \
            -p 27017:27017 \
            mongo:latest
      - name: Realizando Testes
        run: |
          cd ./api
          go test -v ./tests
      - name: Falha nos Testes
        if: failure()
        run: |
          echo "Testes falharam em $(date)"
      - name: Finalizando Testes
        run: |
          echo "Testes finalizados em $(date)"