apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: albums-monitoring
  labels:
    config: grafana
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-svc-clusterip.albums-monitoring.svc.cluster.local:9090
        isDefault: true